### ISSUE TITLE
Git tag info is not getting populated while executing the plugin in google cloud build using maven:3.6.3-openjdk-11

### ISSUE THREAD

**Issue by sgrmgj-quotient** [git-commit-id/git-commit-id-maven-plugin#528]
### the bug
Git tag info is not getting populated while executing the plugin in google cloud build using maven:3.6.3-openjdk-11.
I am trying to use the git properties generated by the plugin in maven build with `<injectAllReactorProjects>true</injectAllReactorProjects>` option. 
The following info is getting populated - 
git.branch
git.commit.id
git.commit.message
but the following are not getting populated only when it runs as a part of google cloud build
    git.closest.tag.name
    git.tags
but the above get populated when I run them locally.

### Steps to Reproduce
```xml
 <plugin>
                <groupId>pl.project13.maven</groupId>
                <artifactId>git-commit-id-plugin</artifactId>
                <version>4.0.2</version>
                <executions>
                    <execution>
                        <id>get-the-git-infos</id>
                        <goals>
                            <goal>revision</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <useNativeGit>true</useNativeGit>
                    <generateGitPropertiesFile>true</generateGitPropertiesFile>
                    <injectAllReactorProjects>true</injectAllReactorProjects>
                    <generateGitPropertiesFilename>${project.build.outputDirectory}/git.properties</generateGitPropertiesFilename>
                    <gitDescribe>
                        <tags>true</tags>
                    </gitDescribe>
                </configuration>
            </plugin> 
```

- Is there a (public) project where this issue can be reproduced? If so please provide a link. 
Unfortunately it's not a public project

- Include any stack-traces or any error messages - 
i don't see any error message

### Expected behavior
- Please provide a description of what you expected to happen.
I expect that the git tag info should be populated.

### Additional context
For reproducibility please provide the following:

- the plugin version is being used (if not included in the configuration) - 4.0.2
- the Java-Version is being used (output of ``java -version`` and also include details about oracle-jdk VS open-jdk) - openjdk11
- the Maven-Version is being used (output of ``mvn --version``) - 3.6.3
- on what Operating System you experience the bug (on Linux run ``lsb_release -a`` or ``cat /etc/*release*``) - I think its linux; amd64
linux; arm64 variant v8
- in what context maven is being executed (e.g. inside Windows Terminal, Powershell, Git Bash, /bin/bash, ...)
Inside google cloud build step - which looks likes this

```
- name: maven:3.6.3-openjdk-11
    entrypoint: mvn
    args: ["clean","package","-DgitTag=${TAG_NAME}","-DgoogleProjectId=${PROJECT_ID}","jib:build","--batch-mode","-DskipTests"]
    volumes:
      - path: '/cache/.m2'
        name: 'm2_cache'
    env:
      - MAVEN_OPTS=-Dmaven.repo.local=/cache/.m2
    id: 'mvn-jib-build'
```

```
- how maven is being executed (e.g. ``mvn clean deploy`` VS ``mvn deploy:deploy``)
mvn package
```
